PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://www.example.org/>

INSERT {
	ex:r3 rdf:type ex:Cubist ;
		ex:first_name "Georges" ;
		ex:last_name "Braque" .
}
WHERE {

}